typedef enum{ATOM, EXPR, SET, FORALL, EXISTS, ALLDIFF, SUM, COMP, COUNT, LET, BOOL2INT, ABS, FMIN, FMAX} nodeType;
typedef enum{PARTYPE, VARTYPE, ARRAY1DTYPE, ARRAY2DTYPE, ARRAY3DTYPE, PAR1DTYPE, PAR2DTYPE,PAR3DTYPE} varType;
typedef enum{NONE, INTTYPE, FLOATTYPE, BOOLTYPE} basicType;

struct Expr_node {
	int a;
} Expr_node;
