/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 171
#define YY_END_OF_BUFFER 172
static yyconst short int yy_accept[471] =
    {   0,
        0,    0,  159,  159,  159,  159,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  172,  170,    3,    2,
      170,  158,  170,   23,  170,  155,  102,   98,   32,  100,
       32,  104,   26,   26,   32,  109,  119,  113,  135,   19,
      170,   21,   36,  170,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,   32,  170,  170,  170,    1,  159,  171,
      168,  166,  168,    1,  167,  168,   16,   18,   17,    1,
        6,    8,    7,    1,   11,   13,   12,    1,  156,  157,
      121,  154,   23,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  106,  123,   33,   14,  131,    0,   26,    0,    0,
        0,   35,  125,  111,  108,  117,  115,  135,   20,  129,
      136,    0,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,   55,   60,  135,  135,  135,  135,
      135,  135,   71,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,   22,  133,  143,    0,    0,    0,    0,
      159,  163,  162,  164,  162,  160,  161,  165,   16,   15,
        6,    5,   11,   10,  154,    0,  103,   99,    0,  101,

        0,    0,  105,    0,  110,    0,    0,  120,    0,  114,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    4,   29,    0,   31,   28,   27,  127,  136,    0,
      169,   37,   39,  135,  135,  135,  135,  135,  135,   45,
      135,  135,  135,  135,  135,  135,  135,  135,   62,   63,
      135,  135,  135,   67,   69,   73,  135,   74,  135,  135,
      135,   78,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,   93,  135,   96,  144,  145,  146,  137,
      138,  139,  142,  147,  148,  153,  152,  149,  150,  151,
      140,  141,  122,  107,  124,   34,  132,  126,    0,  112,

      118,  116,  130,    0,    0,   61,    0,    0,    0,    0,
        0,    0,    0,    0,  134,    9,    0,  135,  135,   41,
       42,  135,  135,   47,   49,  135,   52,  135,  135,  135,
      135,  135,  135,   64,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,   87,   88,   24,  135,   90,
      135,  135,  135,  128,    0,   46,    0,   68,   70,    0,
        0,    0,    0,   97,    0,   30,  135,   40,  135,  135,
      135,   51,   25,   53,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,   79,  135,  135,  135,  135,   89,
       91,  135,   95,   48,    0,    0,    0,    0,    0,  135,

      135,  135,   50,  135,  135,  135,  135,  135,  135,   72,
      135,   76,  135,   80,   81,  135,  135,  135,    0,    0,
        0,    0,   92,  135,  135,   44,  135,   56,  135,  135,
      135,  135,  135,   77,  135,   85,  135,    0,   82,    0,
        0,  135,  135,   54,   57,  135,   65,   66,  135,   83,
      135,    0,    0,   86,  135,  135,   58,   75,  135,    0,
       84,   38,   43,  135,   59,  135,  135,  135,   94,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   14,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   26,   25,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,   29,   30,    1,   31,   32,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   27,   27,   42,   43,   44,
       45,   46,   27,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   14,   56,   14,   57,    1,   58,    1,    1,
       59,    1,    1,   60,   61,   62,   63,   64,    1,    1,
        1,    1,    1,   65,    1,   66,    1,   67,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   68,    1,   69,
        1,    1,    1,   70,   71,    1,   72,   73,   74,   75,
        1,   76,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   77,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   78,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[80] =
    {   0,
        1,    1,    2,    3,    1,    3,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    5,    5,    5,
        1,    1,    1,    1,    6,    6,    6,    1,    3,    1,
        5,    7,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3
    } ;

static yyconst short int yy_base[487] =
    {   0,
        0,    0,   77,   81,   85,   89,   87,   91,   93,   95,
       97,   99,  619,  618,  617,  616,  626,  631,  631,  631,
      602,  631,    0,    0,  174,  631,  631,  611,  631,  599,
      606,   92,   97,  106,  600,  104,  597,  596,    0,  562,
      600,  631,    0,    0,   86,  571,   75,   45,   87,  102,
      101,   60,  108,  570,  108,  104,  577,  155,  176,  569,
      579,  571,  565,  579,  150,  532,  120,  631,    0,  631,
      631,  631,  219,  631,  631,  226,    0,  631,  590,    0,
        0,  631,  589,    0,    0,  631,  588,    0,  631,  631,
      631,    0,    0,  581,  594,  127,  184,  586,  138,  146,

      148,  172,  584,  559,  555,  553,  552,  152,  552,  550,
      226,  631,  631,  631,  582,  631,  201,  224,  238,  193,
      246,  631,  569,  631,  631,  631,  631,    0,  631,  631,
        0,  560,   94,  544,  545,  541,  544,  549,  156,  538,
      149,  543,  539,  539,    0,  224,  533,  533,  527,  535,
      542,  528,    0,  527,  526,  527,  536,  537,  522,  521,
      527,  521,  199,  524,  518,  528,  514,  517,  516,  520,
      513,  522,  511,  631,  631,  631,  211,  227,  221,  186,
        0,  631,  631,  631,  631,  631,  631,  631,    0,  631,
        0,  631,    0,  631,    0,  548,  631,  631,  547,  631,

      546,  545,  631,  544,  631,  228,  543,  631,  542,  631,
      541,  540,  163,  225,  512,  498,  259,  503,  504,  497,
      534,  530,  278,  288,  291,  269,  294,  631,    0,  509,
      631,  495,    0,  506,  496,  500,  488,  502,  496,    0,
      496,  491,  488,  482,  496,  493,  485,  485,  488,    0,
      475,  482,  481,    0,    0,    0,  475,    0,  484,  474,
      477,    0,  466,  475,  467,  477,  477,  463,  467,  473,
      467,  471,  462,  465,  458,    0,  631,  631,  631,  631,
      631,  631,  631,  631,  631,  631,  631,  631,  631,  631,
      631,  631,  631,  631,  631,  631,  631,  631,  495,  631,

      631,  631,  631,  465,  493,  631,  464,  491,  490,  450,
      460,  460,  450,  485,  631,  631,  303,  444,  438,    0,
        0,  442,  440,    0,  448,  450,    0,  450,  437,  436,
      434,  439,  435,    0,  438,  437,  429,  437,  430,  428,
      438,  430,  436,  425,  430,    0,    0,    0,  433,    0,
      425,  435,  430,  631,  457,  631,  418,  631,  631,  427,
      416,  421,  417,  631,  306,  315,  427,    0,  412,  416,
      419,    0,    0,    0,  415,  419,  413,  405,  411,  410,
      401,  414,  412,  409,    0,  407,  396,  396,  405,    0,
        0,  398,    0,  631,  393,  391,  391,  400,  428,  387,

      402,  385,    0,  388,  395,  382,  393,  374,  373,    0,
      394,    0,  372,    0,    0,  388,  386,  374,  385,  412,
      383,  381,  631,  377,  376,    0,  372,    0,  361,  379,
      376,  375,  362,    0,  361,    0,  378,  373,  631,  348,
      386,  345,  344,    0,    0,  334,    0,    0,  344,    0,
      328,  325,  356,  631,  273,  254,    0,    0,  257,  260,
      631,    0,    0,  232,  631,  215,  207,  141,    0,  631,
      335,  342,  349,  356,  169,  363,  366,  153,  106,  372,
      379,  386,  393,  396,  398,  400
    } ;

static yyconst short int yy_def[487] =
    {   0,
      470,    1,  471,  471,  471,  471,  472,  472,  473,  473,
      474,  474,    1,    1,    1,    1,  470,  470,  470,  470,
      470,  470,  475,  476,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  477,  470,
      470,  470,  478,  479,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  470,  470,  470,  470,  470,  480,  470,
      470,  470,  470,  470,  470,  470,  481,  470,  470,  481,
      482,  470,  470,  482,  483,  470,  470,  483,  470,  470,
      470,  484,  476,  470,  470,  470,  470,  470,  470,  470,

      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  477,  470,  470,
      485,  486,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  470,  470,  470,  470,  470,  470,  470,
      480,  470,  470,  470,  470,  470,  470,  470,  481,  470,
      482,  470,  483,  470,  484,  470,  470,  470,  470,  470,

      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  485,  486,
      470,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,

      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  470,  470,  470,  470,  470,  470,  477,

      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  470,  470,
      470,  470,  470,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  470,  470,  470,
      470,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  470,  470,  470,  477,  477,  477,  477,  477,  470,
      470,  477,  477,  477,  470,  477,  477,  477,  477,    0,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470
    } ;

static yyconst short int yy_nxt[711] =
    {   0,
       18,   19,   20,   19,   21,   22,   23,   24,   25,   26,
       18,   27,   28,   29,   30,   31,   32,   33,   34,   34,
       35,   36,   37,   38,   39,   39,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   39,   39,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   39,   39,   64,   65,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   66,   67,   68,   70,
       71,  138,   72,   70,   71,  139,   72,   70,   71,   78,
       75,   70,   71,   78,   75,   82,  147,   82,   79,   86,

      148,   86,   79,  115,   83,   73,   83,  136,   87,   73,
       87,  132,  117,   76,  118,  118,  118,   76,  123,  137,
      116,  117,  119,  118,  118,  118,  124,  125,  140,  133,
      141,  119,  134,  119,  142,  198,  156,  232,  145,  199,
      149,  120,  119,  143,  146,  153,  203,  233,  150,  121,
      157,  144,  151,  154,  205,   74,  208,  155,  131,   74,
      206,  175,  175,   74,  175,   80,  204,   74,  207,   80,
      209,   84,  175,   84,   92,   88,  469,   88,   94,  177,
      210,  178,  179,  180,  242,   95,   96,  159,   97,   98,
       99,  160,  200,  239,  211,  100,  101,  102,  243,  161,

      304,  217,  103,  162,  163,  218,  240,  201,  164,  104,
      226,  226,  165,  305,  105,  166,  106,  107,  223,  223,
      223,  108,  167,  109,  182,  168,  110,  183,  184,  169,
      111,  182,  265,  306,  183,  188,  298,  221,  221,  117,
      221,  118,  118,  118,  266,  291,  292,  185,  221,  119,
      224,  299,  224,  468,  185,  225,  225,  225,  247,  467,
      119,  248,  186,  227,  227,  227,  466,  187,  465,  186,
      227,  227,  249,  307,  187,  277,  278,  279,  227,  227,
      227,  227,  227,  227,  280,  281,  226,  226,  282,  288,
      289,  290,  310,  464,  283,  223,  223,  223,  284,  285,

      286,  287,  463,  317,  311,  225,  225,  225,  225,  225,
      225,  227,  227,  227,  317,  365,  462,  365,  227,  227,
      366,  366,  366,  366,  366,  366,  227,  227,  227,  227,
      227,  227,  366,  366,  366,   69,   69,   69,   69,   69,
       69,   69,   77,   77,   77,   77,   77,   77,   77,   81,
       81,   81,   81,   81,   81,   81,   85,   85,   85,   85,
       85,   85,   85,   93,  461,   93,   93,   93,   93,   93,
      128,  128,  181,  460,  459,  181,  181,  181,  181,  189,
      458,  189,  457,  189,  189,  189,  191,  456,  191,  455,
      191,  191,  191,  193,  454,  193,  453,  193,  193,  193,

      195,  195,  229,  229,  230,  230,  230,  452,  451,  450,
      449,  448,  447,  446,  445,  444,  443,  442,  441,  440,
      439,  438,  437,  436,  435,  434,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      419,  418,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  364,  363,  362,  361,  360,  359,  358,

      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      231,  316,  315,  314,  313,  312,  309,  308,  303,  302,
      301,  300,  297,  296,  295,  294,  293,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  246,  245,  244,  241,  238,  237,  236,  235,
      234,  231,  228,  222,  220,  219,  216,  215,  214,  213,

      212,  202,  197,  196,  194,  192,  190,  176,  174,  173,
      172,  171,  170,  158,  152,  135,  130,  129,  127,  126,
      122,  114,  113,  112,   91,  470,   90,   90,   89,   89,
       17,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,

      470,  470,  470,  470,  470,  470,  470,  470,  470,  470
    } ;

static yyconst short int yy_chk[711] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,   48,    3,    4,    4,   48,    4,    5,    5,    7,
        5,    6,    6,    8,    6,    9,   52,   10,    7,   11,

       52,   12,    8,   32,    9,    3,   10,   47,   11,    4,
       12,  479,   33,    5,   33,   33,   33,    6,   36,   47,
       32,   34,   33,   34,   34,   34,   36,   36,   49,   45,
       49,   34,   45,   33,   50,   96,   56,  133,   51,   96,
       53,   33,   34,   50,   51,   55,   99,  133,   53,   33,
       56,   50,   53,   55,  100,    3,  101,   55,  478,    4,
      100,   65,   65,    5,   65,    7,   99,    6,  100,    8,
      101,    9,   65,   10,  475,   11,  468,   12,   25,   67,
      102,   67,   67,   67,  141,   25,   25,   58,   25,   25,
       25,   58,   97,  139,  102,   25,   25,   25,  141,   58,

      213,  108,   25,   58,   58,  108,  139,   97,   58,   25,
      120,  120,   59,  213,   25,   59,   25,   25,  117,  117,
      117,   25,   59,   25,   73,   59,   25,   73,   73,   59,
       25,   76,  163,  214,   76,   76,  206,  111,  111,  118,
      111,  118,  118,  118,  163,  180,  180,   73,  111,  118,
      119,  206,  119,  467,   76,  119,  119,  119,  146,  466,
      118,  146,   73,  121,  121,  121,  464,   73,  460,   76,
      121,  121,  146,  214,   76,  177,  177,  177,  121,  121,
      121,  121,  121,  121,  178,  178,  226,  226,  178,  179,
      179,  179,  217,  459,  178,  223,  223,  223,  178,  178,

      178,  178,  456,  223,  217,  224,  224,  224,  225,  225,
      225,  227,  227,  227,  223,  317,  455,  317,  227,  227,
      317,  317,  317,  365,  365,  365,  227,  227,  227,  227,
      227,  227,  366,  366,  366,  471,  471,  471,  471,  471,
      471,  471,  472,  472,  472,  472,  472,  472,  472,  473,
      473,  473,  473,  473,  473,  473,  474,  474,  474,  474,
      474,  474,  474,  476,  453,  476,  476,  476,  476,  476,
      477,  477,  480,  452,  451,  480,  480,  480,  480,  481,
      449,  481,  446,  481,  481,  481,  482,  443,  482,  442,
      482,  482,  482,  483,  441,  483,  440,  483,  483,  483,

      484,  484,  485,  485,  486,  486,  486,  438,  437,  435,
      433,  432,  431,  430,  429,  427,  425,  424,  422,  421,
      420,  419,  418,  417,  416,  413,  411,  409,  408,  407,
      406,  405,  404,  402,  401,  400,  399,  398,  397,  396,
      395,  392,  389,  388,  387,  386,  384,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  371,  370,  369,  367,
      363,  362,  361,  360,  357,  355,  353,  352,  351,  349,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  333,  332,  331,  330,  329,  328,  326,  325,  323,
      322,  319,  318,  314,  313,  312,  311,  310,  309,  308,

      307,  305,  304,  299,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  261,  260,  259,
      257,  253,  252,  251,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  239,  238,  237,  236,  235,  234,  232,
      230,  222,  221,  220,  219,  218,  216,  215,  212,  211,
      209,  207,  204,  202,  201,  199,  196,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  152,  151,  150,  149,
      148,  147,  144,  143,  142,  140,  138,  137,  136,  135,
      134,  132,  123,  115,  110,  109,  107,  106,  105,  104,

      103,   98,   95,   94,   87,   83,   79,   66,   64,   63,
       62,   61,   60,   57,   54,   46,   41,   40,   38,   37,
       35,   31,   30,   28,   21,   17,   16,   15,   14,   13,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      470,  470,  470,  470,  470,  470,  470,  470,  470,  470,

      470,  470,  470,  470,  470,  470,  470,  470,  470,  470
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
/*********************************************************************** 
 * lexer.l                                                             *
 *                                                                     *
 * Copyright (C) 2015 Luca Gasparetto                                  *
 * All rights reserved.                                                *
 *                                                                     *
 * This software may be modified and distributed under the terms       *
 * of the MIT license.  See the LICENSE file for details.              *
 ***********************************************************************/
#line 12 "lexer.l"
	#include "calc.h"
	#include "parser.tab.h"
#define string 1

#define string_quote 2

#define multilinecomment 3

#define doccomment 4

#define doccomment_file 5

#define bracket_exp 6

#define quoted_exp 7

#line 707 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 24 "lexer.l"


#line 872 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 471 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 631 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "lexer.l"
{
						return MZN_INVALID_NULL;
					}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "lexer.l"
{
						
                  	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "lexer.l"
{/* ignore whitespace */}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "lexer.l"
{}
	YY_BREAK

case 5:
YY_RULE_SETUP
#line 37 "lexer.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 38 "lexer.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 39 "lexer.l"
{}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 40 "lexer.l"
{}
	YY_BREAK

case 9:
YY_RULE_SETUP
#line 43 "lexer.l"
{}
	YY_BREAK

case 10:
YY_RULE_SETUP
#line 45 "lexer.l"
{return MZN_DOC_FILE_COMMENT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "lexer.l"
{}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "lexer.l"
{}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "lexer.l"
{}
	YY_BREAK

case 14:
YY_RULE_SETUP
#line 51 "lexer.l"
{}
	YY_BREAK

case 15:
YY_RULE_SETUP
#line 53 "lexer.l"
{}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "lexer.l"
{}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "lexer.l"
{}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "lexer.l"
{}
	YY_BREAK

case 19:
YY_RULE_SETUP
#line 60 "lexer.l"
{ return MZN_LEFT_BRACKET; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "lexer.l"
{ return MZN_LEFT_2D_BRACKET; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "lexer.l"
{ return MZN_RIGHT_BRACKET; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "lexer.l"
{ return MZN_RIGHT_2D_BRACKET; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "lexer.l"
{ /* ignore comments */ }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "lexer.l"
{ //yylval.literal.litType = BOOLTYPE;
					//yylval.literal.bValue = 1;					
					return MZN_BOOL_LITERAL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 69 "lexer.l"
{ //yylval.literal.litType = BOOLTYPE;
					//yylval.literal.bValue = 0;					
					return MZN_BOOL_LITERAL; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 72 "lexer.l"
{	//yylval.literal.litType = INTTYPE;
					//yylval.literal.iValue = atoi(yytext);					
					return MZN_INTEGER_LITERAL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 75 "lexer.l"
{ //BASE 16
					//yylval.literal.litType = INTTYPE;
					//yylval.literal.iValue = strtol(yytext, NULL, 16);					
					return MZN_INTEGER_LITERAL;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "lexer.l"
{ //BASE 8
					//yylval.literal.litType = INTTYPE;
					//yylval.literal.iValue = strtol(yytext, NULL, 8);					
					return MZN_INTEGER_LITERAL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "lexer.l"
{ //yylval.literal.litType = FLOATTYPE;
					//yylval.literal.fValue = atof(yytext);					
					return MZN_FLOAT_LITERAL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 86 "lexer.l"
{
                    //yylval.literal.litType = FLOATTYPE;
					//yylval.literal.fValue = atof(yytext);					
					return MZN_FLOAT_LITERAL;
                   }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 91 "lexer.l"
{
                    //yylval.literal.litType = FLOATTYPE;
					//yylval.literal.fValue = atof(yytext);					
					return MZN_FLOAT_LITERAL;
                   }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "lexer.l"
{ return *yytext; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 97 "lexer.l"
{ return MZN_DOTDOT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 98 "lexer.l"
{ return MZN_DOTDOT_QUOTED; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 99 "lexer.l"
{ return MZN_COLONCOLON; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 100 "lexer.l"
{ return MZN_UNDERSCORE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 101 "lexer.l"
{ return MZN_ANN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 102 "lexer.l"
{ return MZN_ANNOTATION; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return MZN_ANY; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 104 "lexer.l"
{ return MZN_ARRAY; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 105 "lexer.l"
{ return MZN_BOOL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return MZN_CASE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return MZN_CONSTRAINT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return MZN_DEFAULT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return MZN_IDIV; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return MZN_IDIV_QUOTED; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return MZN_DIFF; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return MZN_DIFF_QUOTED; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return MZN_ELSE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 114 "lexer.l"
{ return MZN_ELSEIF; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return MZN_ENDIF; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return MZN_ENUM; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return MZN_FLOAT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return MZN_FUNCTION; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 119 "lexer.l"
{ return MZN_IF; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return MZN_INCLUDE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return MZN_INFINITY; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 122 "lexer.l"
{ return MZN_INTERSECT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 123 "lexer.l"
{ return MZN_INTERSECT_QUOTED; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 124 "lexer.l"
{ return MZN_IN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 125 "lexer.l"
{ return MZN_IN_QUOTED; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return MZN_INT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 127 "lexer.l"
{ return MZN_LET; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return MZN_LIST; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 129 "lexer.l"
{ return MZN_MAXIMIZE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 130 "lexer.l"
{ return MZN_MINIMIZE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 131 "lexer.l"
{ return MZN_MOD; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return MZN_MOD_QUOTED; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return MZN_NOT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return MZN_NOT_QUOTED; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return MZN_OF; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 136 "lexer.l"
{ return MZN_OUTPUT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 137 "lexer.l"
{ return MZN_OPT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 138 "lexer.l"
{ return MZN_PAR; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 139 "lexer.l"
{ return MZN_PREDICATE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 140 "lexer.l"
{ return MZN_RECORD; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 141 "lexer.l"
{ return MZN_SATISFY; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 142 "lexer.l"
{ return MZN_SET; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return MZN_SOLVE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 144 "lexer.l"
{ return MZN_STRING; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 145 "lexer.l"
{ return MZN_SUBSET; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 146 "lexer.l"
{ return MZN_SUBSET_QUOTED; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 147 "lexer.l"
{ return MZN_SUPERSET; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 148 "lexer.l"
{ return MZN_SUPERSET_QUOTED; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 149 "lexer.l"
{ return MZN_SYMDIFF; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 150 "lexer.l"
{ return MZN_SYMDIFF_QUOTED; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 151 "lexer.l"
{ return MZN_TEST; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 152 "lexer.l"
{ return MZN_THEN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 153 "lexer.l"
{ return MZN_TUPLE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 154 "lexer.l"
{ return MZN_TYPE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 155 "lexer.l"
{ return MZN_UNION; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 156 "lexer.l"
{ return MZN_UNION_QUOTED; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 157 "lexer.l"
{ return MZN_VAR; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 158 "lexer.l"
{ return MZN_VARIANT_RECORD; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 159 "lexer.l"
{ return MZN_WHERE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 160 "lexer.l"
{ return MZN_XOR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 161 "lexer.l"
{ return MZN_XOR_QUOTED; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 162 "lexer.l"
{ return MZN_PLUS; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 163 "lexer.l"
{ return MZN_PLUS_QUOTED; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 164 "lexer.l"
{ return MZN_MINUS; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 165 "lexer.l"
{ return MZN_MINUS_QUOTED; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 166 "lexer.l"
{ return MZN_MULT; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 167 "lexer.l"
{ return MZN_MULT_QUOTED; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 168 "lexer.l"
{ return MZN_DIV; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 169 "lexer.l"
{ return MZN_DIV_QUOTED; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 170 "lexer.l"
{ return MZN_PLUSPLUS; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 171 "lexer.l"
{ return MZN_PLUSPLUS_QUOTED; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 172 "lexer.l"
{ return MZN_ABSENT; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 173 "lexer.l"
{ return MZN_LE; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 174 "lexer.l"
{ return MZN_LE_QUOTED; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 175 "lexer.l"
{ return MZN_LQ; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 176 "lexer.l"
{ return MZN_LQ_QUOTED; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 177 "lexer.l"
{ return MZN_GR; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 178 "lexer.l"
{ return MZN_GR_QUOTED; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 179 "lexer.l"
{ return MZN_GQ; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 180 "lexer.l"
{ return MZN_GQ_QUOTED; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 181 "lexer.l"
{ return MZN_EQ; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 182 "lexer.l"
{ return MZN_EQ_QUOTED; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 183 "lexer.l"
{ return MZN_EQ; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 184 "lexer.l"
{ return MZN_EQ_QUOTED; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 185 "lexer.l"
{ return MZN_NQ; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 186 "lexer.l"
{ return MZN_NQ_QUOTED; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 187 "lexer.l"
{ return MZN_IMPL; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 188 "lexer.l"
{ return MZN_IMPL_QUOTED; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 189 "lexer.l"
{ return MZN_RIMPL; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 190 "lexer.l"
{ return MZN_RIMPL_QUOTED; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 191 "lexer.l"
{ return MZN_EQUIV; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 192 "lexer.l"
{ return MZN_EQUIV_QUOTED; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 193 "lexer.l"
{ return MZN_OR; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 194 "lexer.l"
{ return MZN_OR_QUOTED; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 195 "lexer.l"
{ return MZN_AND; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 196 "lexer.l"
{ return MZN_AND_QUOTED; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 198 "lexer.l"
{ return MZN_QUOTED_IDENTIFIER; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 199 "lexer.l"
{ return MZN_IDENTIFIER; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 201 "lexer.l"
{ 
					//yylval.ident = (char*) malloc(sizeof(char)*(strlen(yytext)+1));
					//strcpy(yylval.ident, yytext);
					//sprintf(yylval.ident, "%s\0",yytext);
                   	return MZN_IDENTIFIER; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 206 "lexer.l"
{
                    	return FLATZINC_IDENTIFIER;
                    }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 211 "lexer.l"
{  	//yylval.ident = (char*) malloc(sizeof(char)*(strlen(yytext)+1));
					   	//strcpy(yylval.ident, yytext);
					   	return MZN_IDENTIFIER; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 214 "lexer.l"
{  	//yylval.ident = (char*) malloc(sizeof(char)*(strlen(yytext)+1));
						//strcpy(yylval.ident, yytext);
						return MZN_IDENTIFIER; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 217 "lexer.l"
{ return MZN_IN; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 218 "lexer.l"
{ return MZN_SUBSET; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 219 "lexer.l"
{ return MZN_SUPERSET; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 220 "lexer.l"
{ return MZN_INFINITY; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 221 "lexer.l"
{ return MZN_NOT; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 222 "lexer.l"
{ return MZN_RIMPL; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 223 "lexer.l"
{ return MZN_IMPL; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 224 "lexer.l"
{ return MZN_EQUIV; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 225 "lexer.l"
{ return MZN_AND; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 226 "lexer.l"
{ return MZN_OR; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 227 "lexer.l"
{ return MZN_NQ; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 228 "lexer.l"
{ return MZN_LQ; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 229 "lexer.l"
{ return MZN_GQ; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 230 "lexer.l"
{ return MZN_UNION; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 231 "lexer.l"
{ return MZN_INTERSECT; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 233 "lexer.l"
{
                    return MZN_TI_IDENTIFIER; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 236 "lexer.l"
{  return *yytext; }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 237 "lexer.l"
{  return *yytext; }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 238 "lexer.l"
{ }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 240 "lexer.l"
{}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 241 "lexer.l"
{}
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 242 "lexer.l"
{}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 243 "lexer.l"
{}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 244 "lexer.l"
{}
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 245 "lexer.l"
{}
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 246 "lexer.l"
{ return MZN_STRING_QUOTE_START; }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 247 "lexer.l"
{ return MZN_STRING_QUOTE_MID;}
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 248 "lexer.l"
{ return MZN_STRING_LITERAL; }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 249 "lexer.l"
{ return MZN_STRING_QUOTE_END; }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 250 "lexer.l"
{  return (unsigned char)yytext[0]; }
	YY_BREAK
case YY_STATE_EOF(string):
case YY_STATE_EOF(string_quote):
#line 251 "lexer.l"
{  return MZN_UNTERMINATED_STRING; }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 253 "lexer.l"
{return MZN_QUOTED_IDENTIFIER; }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 254 "lexer.l"
{ return (unsigned char)yytext[0]; }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 257 "lexer.l"
ECHO;
	YY_BREAK
#line 1858 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(multilinecomment):
case YY_STATE_EOF(doccomment):
case YY_STATE_EOF(doccomment_file):
case YY_STATE_EOF(bracket_exp):
case YY_STATE_EOF(quoted_exp):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 79);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 471 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 79;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 471 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 470);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 257 "lexer.l"


void yyerror(const char* s){
	//fprintf(stdout, "%s\n", s);
	printf(": %s at %s\n", s, yytext);
}
int yywrap()
{
	return 1;
}
